import { FilterState } from '../types';
import { computeAggregates, FACILITIES, ALL_MONTHLY_DATA, MONTH_LABELS } from '../data/mockData';
import { evaluateBenchmark } from '../data/benchmarks';

export interface RagResponse {
  answer: string;
  observations: string[];
  benchmarkComparison?: {
    metric: string;
    currentValue: string;
    target: string;
    variance: string;
    status: 'success' | 'warning' | 'critical';
  };
  trendAssessment?: {
    direction: 'Improving' | 'Declining' | 'Stable';
    detail: string;
  };
  facilitiesToWatch?: {
    name: string;
    state: string;
    metricLabel: string;
    value: string;
    issue: string;
  }[];
  suggestedFollowUp?: string;
  safetyNote?: string;
}

export function queryRagAssistant(
  question: string,
  filters: FilterState,
  onResetFilters?: () => void
): RagResponse {
  const q = question.toLowerCase().trim();
  const aggregates = computeAggregates(filters);

  // Safety boundary check: Individual diagnosis or clinical risk queries
  if (
    q.includes('diagnos') ||
    q.includes('prescribe') ||
    q.includes('medication') ||
    q.includes('dosage') ||
    q.includes('clinical treatment for') ||
    q.includes('patient name') ||
    q.includes('change risk') ||
    q.includes('reclassify') ||
    q.includes('override ars')
  ) {
    return {
      answer:
        'I can help explain programme-level trends and dashboard data, but I cannot determine individual clinical risk, provide medical diagnosis, or recommend patient-specific treatment.',
      observations: [
        'All patient risk classifications shown across this dashboard are generated by the validated ARS clinical tool.',
        'HeliumMum AI functions strictly as an analytical decision-support layer for public health officers and programme managers.',
        'Patient identifiers are completely anonymized to protect maternal confidentiality.',
      ],
      safetyNote:
        'ARS Risk classifications are clinically validated. AI cannot alter, override, or diagnose individual cases.',
      suggestedFollowUp:
        'Consult with facility clinical directors or maternal health lead specialists for individual patient management.',
    };
  }

  // 1. Lowest ANC completion rate state / state comparison
  if (q.includes('lowest anc') || q.includes('lowest completion') || q.includes('which state has the lowest')) {
    // Compare states
    const states: ('Lagos' | 'Delta' | 'Kano' | 'Ekiti')[] = ['Lagos', 'Delta', 'Kano', 'Ekiti'];
    const stateStats = states.map((st) => {
      const stAgg = computeAggregates({ ...filters, selectedState: st, selectedFacilityId: 'All' });
      return {
        state: st,
        completion: stAgg.avgAncCompletion,
        registered: stAgg.womenRegistered,
        earlyBooking: stAgg.avgEarlyBooking,
      };
    }).sort((a, b) => a.completion - b.completion);

    const lowest = stateStats[0];
    const highest = stateStats[stateStats.length - 1];

    return {
      answer: `${lowest.state} State currently records the lowest ANC 8-visit completion rate at ${lowest.completion}%, compared to the programme benchmark of 70%.`,
      observations: [
        `${lowest.state} achieves ${lowest.completion}% completion across its ${filters.dateRange.toUpperCase()} window, lagging ${highest.state} which leads at ${highest.completion}%.`,
        `Primary attrition occurs between ANC Visit 2 and Visit 4, driven by transport barriers and delayed 1st trimester booking (${lowest.earlyBooking}% early booking).`,
        `A total of ${lowest.registered.toLocaleString()} registered pregnant women are being monitored in ${lowest.state}.`,
      ],
      benchmarkComparison: {
        metric: 'ANC 8-Visit Completion',
        currentValue: `${lowest.completion}%`,
        target: '≥ 70%',
        variance: `${lowest.completion - 70} pts below target`,
        status: lowest.completion >= 70 ? 'success' : lowest.completion >= 65 ? 'warning' : 'critical',
      },
      trendAssessment: {
        direction: 'Declining',
        detail: `${lowest.state} has experienced a -2.4 pt shift over the prior equivalent window.`,
      },
      facilitiesToWatch: aggregates.facilityAncRankings.slice(0, 3).map((f) => ({
        name: f.name,
        state: f.state,
        metricLabel: 'ANC Completion',
        value: `${f.completionRate}%`,
        issue: 'Critical drop-off after second trimester visit',
      })),
      suggestedFollowUp:
        'Deploy targeted Community Health Extension Workers (CHEWs) for home-visit retention reminders prior to week 20 of gestation.',
    };
  }

  // 2. Facilities below ANC completion target
  if (
    q.includes('below the anc') ||
    q.includes('below target') ||
    q.includes('underperforming') ||
    q.includes('below anc completion')
  ) {
    const underperforming = aggregates.facilityAncRankings.filter((f) => f.completionRate < 70);
    return {
      answer: `There are ${underperforming.length} facilities currently performing below the 70% ANC completion target in the active filter scope (${filters.selectedState !== 'All' ? filters.selectedState : 'All States'}).`,
      observations: [
        `The bottom-ranking facility is ${underperforming[0]?.name || 'N/A'} at ${underperforming[0]?.completionRate || 0}% completion.`,
        `Facilities with fewer skilled attendants (< 12) exhibit a 14-point lower retention rate on average.`,
        `Drop-off is most pronounced between Visit 2 and Visit 3 across all ${underperforming.length} flagged centres.`,
      ],
      benchmarkComparison: {
        metric: 'ANC Completion Target',
        currentValue: `${aggregates.avgAncCompletion}% (Scope Average)`,
        target: '≥ 70%',
        variance: `${aggregates.avgAncCompletion - 70} pts vs target`,
        status: aggregates.avgAncCompletion >= 70 ? 'success' : 'warning',
      },
      trendAssessment: {
        direction: aggregates.avgAncCompletionDelta >= 0 ? 'Improving' : 'Declining',
        detail: `${aggregates.avgAncCompletionDelta >= 0 ? '+' : ''}${aggregates.avgAncCompletionDelta} pts vs prior period`,
      },
      facilitiesToWatch: underperforming.slice(0, 4).map((f) => ({
        name: f.name,
        state: f.state,
        metricLabel: 'Completion Rate',
        value: `${f.completionRate}%`,
        issue: `Deficit of ${70 - f.completionRate} pts from benchmark`,
      })),
      suggestedFollowUp:
        'Prioritize supervisory mentoring visits by the State Primary Health Care Board to these facilities.',
    };
  }

  // 3. Facility delivery trend / why changed
  if (
    q.includes('facility delivery') ||
    q.includes('delivery trend') ||
    q.includes('why has facility delivery')
  ) {
    const deliveryEval = evaluateBenchmark('facilityDelivery', aggregates.facilityDeliveryRate);
    const formalCount = aggregates.deliveries.formalFacility;
    const tbaCount = aggregates.deliveries.tba;
    const transferredCount = aggregates.deliveries.transferred;

    return {
      answer: `Facility delivery currently stands at ${aggregates.facilityDeliveryRate}%, with ${formalCount.toLocaleString()} formal facility deliveries, ${tbaCount.toLocaleString()} TBA births, and ${transferredCount.toLocaleString()} emergency transfers recorded.`,
      observations: [
        `Formal deliveries represent ${aggregates.facilityDeliveryRate}% of all recorded births, compared to the programme benchmark of 80%.`,
        `Recent shifts correlate with community engagement initiatives and expanded skilled midwife shifts in secondary maternity centres.`,
        `TBA deliveries account for ${Math.round((tbaCount / Math.max(1, aggregates.deliveries.total)) * 100)}% of births, requiring active traditional birth attendant integration.`,
      ],
      benchmarkComparison: {
        metric: 'Formal Facility Delivery',
        currentValue: `${aggregates.facilityDeliveryRate}%`,
        target: '≥ 80%',
        variance: deliveryEval.varianceFormatted,
        status: deliveryEval.status,
      },
      trendAssessment: {
        direction: aggregates.facilityDeliveryRateDelta >= 0 ? 'Improving' : 'Declining',
        detail: `${aggregates.facilityDeliveryRateDelta >= 0 ? '+' : ''}${aggregates.facilityDeliveryRateDelta} pts vs previous period`,
      },
      facilitiesToWatch: aggregates.facilityAncRankings
        .filter((f) => !f.hasBloodBank)
        .slice(0, 3)
        .map((f) => ({
          name: f.name,
          state: f.state,
          metricLabel: 'Attendants / Readiness',
          value: `${f.skilledAttendants} staff`,
          issue: 'No dedicated blood bank on site; higher complication referral rate',
        })),
      suggestedFollowUp:
        'Establish transportation subsidy vouchers for mothers in rural LGAs to sustain formal delivery uptake.',
    };
  }

  // 4. Maternal mortality incidence trending
  if (
    q.includes('maternal mortality') ||
    q.includes('mortality incidence') ||
    q.includes('deaths') ||
    q.includes('how is maternal mortality')
  ) {
    const incidenceEval = evaluateBenchmark(
      'maternalMortalityIncidence',
      aggregates.recordedMortalityIncidence
    );
    return {
      answer: `Recorded maternal mortality incidence is currently ${aggregates.recordedMortalityIncidence} per 100,000 deliveries (${aggregates.totalMaternalDeaths} deaths among ${aggregates.deliveries.total.toLocaleString()} recorded deliveries), well within the programme threshold of ≤ 120 per 100k.`,
      observations: [
        `Maternal deaths remain rare across all monitored facilities, reflecting early clinical risk triage by the ARS algorithm.`,
        `Leading contributing factors identified in clinical audits are: ${aggregates.deathContributingFactors[0]?.factor || 'Delayed Referral'} and ${aggregates.deathContributingFactors[1]?.factor || 'Blood Bank Stockout'}.`,
        `This metric represents recorded facility deaths and is not an official population-level maternal mortality ratio.`,
      ],
      benchmarkComparison: {
        metric: 'Recorded Mortality Incidence',
        currentValue: `${aggregates.recordedMortalityIncidence} / 100k`,
        target: '≤ 120 / 100k',
        variance: incidenceEval.varianceFormatted,
        status: incidenceEval.status,
      },
      trendAssessment: {
        direction: aggregates.mortalityIncidenceDelta <= 0 ? 'Improving' : 'Declining',
        detail: `${aggregates.mortalityIncidenceDelta <= 0 ? '' : '+'}${aggregates.mortalityIncidenceDelta} pts vs previous period`,
      },
      facilitiesToWatch: aggregates.facilities
        .filter((f) => !f.hasBloodBank)
        .slice(0, 3)
        .map((f) => ({
          name: f.name,
          state: f.state,
          metricLabel: 'Emergency Readiness',
          value: 'No Blood Bank',
          issue: 'Vulnerable to delayed treatment in severe postpartum hemorrhage',
        })),
      suggestedFollowUp:
        'Ensure 100% of high-risk mothers identified in the ARS tool have pre-matched emergency donor protocols in place by gestational week 32.',
    };
  }

  // 5. Reasons for complication referrals
  if (
    q.includes('referral') ||
    q.includes('transfer reasons') ||
    q.includes('complication')
  ) {
    const topReason = aggregates.transferReasons[0];
    const secondReason = aggregates.transferReasons[1];
    return {
      answer: `The leading clinical reason for complication transfers is ${topReason?.reason || 'Obstructed Labor'} (${topReason?.count || 0} cases), followed by ${secondReason?.reason || 'Postpartum Hemorrhage'} (${secondReason?.count || 0} cases).`,
      observations: [
        `${topReason?.reason} accounts for the highest volume of facility-to-tertiary transfers.`,
        `Severe Eclampsia and Hypertensive emergencies triggered ${aggregates.transferReasons.find((r) => r.reason.toLowerCase().includes('eclampsia'))?.count || 0} emergency transfers.`,
        `Overall referral completion rate is ${aggregates.referralCompletionRate}%, meeting the ≥ 90% benchmark for tertiary care reception.`,
      ],
      benchmarkComparison: {
        metric: 'Referral Completion Rate',
        currentValue: `${aggregates.referralCompletionRate}%`,
        target: '≥ 90%',
        variance: `${aggregates.referralCompletionRate - 90} pts vs target`,
        status: aggregates.referralCompletionRate >= 90 ? 'success' : 'warning',
      },
      trendAssessment: {
        direction: 'Stable',
        detail: 'Referral transfer tracking protocol remains consistent across facilities.',
      },
      suggestedFollowUp:
        'Standardize emergency transit fuel stipends at primary health centres to eliminate transit delays during second-stage labor arrest.',
    };
  }

  // 6. Compare Lagos and Delta
  if (q.includes('compare lagos and delta') || (q.includes('lagos') && q.includes('delta'))) {
    const lagAgg = computeAggregates({ ...filters, selectedState: 'Lagos', selectedFacilityId: 'All' });
    const delAgg = computeAggregates({ ...filters, selectedState: 'Delta', selectedFacilityId: 'All' });

    return {
      answer: `Comparison between Lagos and Delta: Lagos records higher 1st trimester early booking (${lagAgg.avgEarlyBooking}% vs ${delAgg.avgEarlyBooking}%), while Delta maintains strong facility delivery at ${delAgg.facilityDeliveryRate}% (vs ${lagAgg.facilityDeliveryRate}% in Lagos).`,
      observations: [
        `ANC 8-Visit Completion: Lagos ${lagAgg.avgAncCompletion}% vs Delta ${delAgg.avgAncCompletion}%.`,
        `Women Registered: Lagos has ${lagAgg.womenRegistered.toLocaleString()} vs Delta's ${delAgg.womenRegistered.toLocaleString()}.`,
        `Reporting Compliance: Lagos facilities reported ${lagAgg.onTimeReports} on-time submissions vs Delta's ${delAgg.onTimeReports}.`,
        `Recorded Mortality Incidence: Lagos is ${lagAgg.recordedMortalityIncidence}/100k vs Delta's ${delAgg.recordedMortalityIncidence}/100k.`,
      ],
      benchmarkComparison: {
        metric: 'Comparative ANC Completion',
        currentValue: `Lagos: ${lagAgg.avgAncCompletion}% | Delta: ${delAgg.avgAncCompletion}%`,
        target: '≥ 70%',
        variance: `Lagos ${lagAgg.avgAncCompletion - 70} pts | Delta ${delAgg.avgAncCompletion - 70} pts`,
        status: lagAgg.avgAncCompletion >= 70 && delAgg.avgAncCompletion >= 70 ? 'success' : 'warning',
      },
      suggestedFollowUp:
        'Implement peer learning sessions where Delta sharing operational strategies for facility delivery with Lagos urban centres.',
    };
  }

  // 7. Low ANC and Late reporting facilities
  if (q.includes('late reporting') || q.includes('both low anc') || q.includes('reporting')) {
    const problematic = aggregates.facilityAncRankings
      .filter((f) => f.completionRate < 70)
      .slice(0, 3);
    return {
      answer: `There are 3 priority facilities displaying both suboptimal ANC completion and recurring late monthly reporting submissions.`,
      observations: [
        `Latest month on-time reporting rate across the scope is ${aggregates.latestMonthOnTimeRate}% (${aggregates.latestMonthOnTimeCount}/${aggregates.latestMonthTotal} facilities).`,
        `Delayed data submissions directly impair early surveillance of high-risk pregnancies by the Ministry.`,
        `Staff shortages and rural connectivity issues are the primary reported barriers to timely digital submission.`,
      ],
      benchmarkComparison: {
        metric: 'On-Time Facility Reporting',
        currentValue: `${aggregates.latestMonthOnTimeRate}%`,
        target: '≥ 90%',
        variance: `${aggregates.latestMonthOnTimeRate - 90} pts vs target`,
        status: aggregates.latestMonthOnTimeRate >= 90 ? 'success' : 'warning',
      },
      facilitiesToWatch: problematic.map((f) => ({
        name: f.name,
        state: f.state,
        metricLabel: 'Completion / Status',
        value: `${f.completionRate}% completion`,
        issue: 'Frequent late monthly reporting submissions',
      })),
      suggestedFollowUp:
        'Equip designated facility record officers with offline-first HeliumMum data synchronizers and mobile data allowances.',
    };
  }

  // 8. What changed in Lagos this quarter / state specific
  if (q.includes('lagos') && (q.includes('changed') || q.includes('quarter'))) {
    const lagAgg = computeAggregates({ ...filters, selectedState: 'Lagos', selectedFacilityId: 'All' });
    return {
      answer: `In Lagos State over the evaluated period, pregnant women registration reached ${lagAgg.womenRegistered.toLocaleString()}, with ANC completion advancing to ${lagAgg.avgAncCompletion}% (${lagAgg.avgAncCompletionDelta >= 0 ? '+' : ''}${lagAgg.avgAncCompletionDelta} pts vs previous period).`,
      observations: [
        `Early ANC booking in the 1st trimester climbed to ${lagAgg.avgEarlyBooking}%, surpassing the 60% benchmark.`,
        `High-risk follow-up compliance reached ${lagAgg.highRiskFollowUpRate}%, closely aligning with the ≥ 90% target.`,
        `Island Maternity Hospital and Alimosho General Hospital demonstrated the strongest retention across all 8 visits.`,
      ],
      benchmarkComparison: {
        metric: 'Lagos ANC Completion',
        currentValue: `${lagAgg.avgAncCompletion}%`,
        target: '≥ 70%',
        variance: `${lagAgg.avgAncCompletion - 70} pts vs target`,
        status: lagAgg.avgAncCompletion >= 70 ? 'success' : 'warning',
      },
      trendAssessment: {
        direction: lagAgg.avgAncCompletionDelta >= 0 ? 'Improving' : 'Declining',
        detail: `${lagAgg.avgAncCompletionDelta >= 0 ? '+' : ''}${lagAgg.avgAncCompletionDelta} pts improvement`,
      },
      suggestedFollowUp:
        'Scale the Island Maternity two-way SMS reminder pilot to Surulere and Ikorodu LGA facilities.',
    };
  }

  // 9. Largest improvement facilities
  if (q.includes('improvement') || q.includes('largest improvement') || q.includes('top performing')) {
    const topFacilities = [...aggregates.facilityAncRankings].reverse().slice(0, 5);
    return {
      answer: `The top 5 performing facilities with the highest ANC completion and clinical retention are led by ${topFacilities[0]?.name || 'Island Maternity Hospital'} (${topFacilities[0]?.completionRate || 82}% completion).`,
      observations: [
        `Top facilities maintain active midwife task-sharing and automated ARS high-risk alerts.`,
        `Average 8-visit completion among top centres is ${Math.round(topFacilities.reduce((s, f) => s + f.completionRate, 0) / topFacilities.length)}%, exceeding the programme benchmark by over 10 points.`,
        `All 5 top facilities have functioning blood bank agreements and at least 15 skilled birth attendants.`,
      ],
      facilitiesToWatch: topFacilities.map((f) => ({
        name: f.name,
        state: f.state,
        metricLabel: 'ANC Completion',
        value: `${f.completionRate}%`,
        issue: 'Exemplary benchmark compliance',
      })),
      suggestedFollowUp:
        'Recognize leadership at these facilities during the State Maternal Health Quarterly Review.',
    };
  }

  // 10. What should I pay attention to this month?
  if (q.includes('pay attention') || q.includes('attention') || q.includes('priority')) {
    const drop = aggregates.biggestDrop;
    return {
      answer: `Immediate attention is required on three operational focal areas: (1) The maternal visit drop-off between ${drop.from} and ${drop.to}, (2) Facilities lacking blood bank access, and (3) Closing the ${aggregates.avgAncCompletion < 70 ? 'deficit' : 'gap'} in ANC 8-visit completion.`,
      observations: [
        `The largest drop-off occurs between ${drop.from} and ${drop.to}, where ${Math.round(drop.pct)}% of women do not return.`,
        `Blood bank stockouts contributed to ${aggregates.deathContributingFactors.find((f) => f.factor.includes('Blood'))?.count || 0} critical complication events.`,
        `On-time facility reporting currently stands at ${aggregates.latestMonthOnTimeRate}%, with ${aggregates.latestMonthTotal - aggregates.latestMonthOnTimeCount} facilities reporting late or missing.`,
      ],
      benchmarkComparison: {
        metric: 'ANC 8-Visit Completion',
        currentValue: `${aggregates.avgAncCompletion}%`,
        target: '≥ 70%',
        variance: `${aggregates.avgAncCompletion - 70} pts vs target`,
        status: aggregates.avgAncCompletion >= 70 ? 'success' : 'warning',
      },
      suggestedFollowUp:
        'Initiate contact tracing for women currently overdue for Visit 3 and reinforce emergency blood dispatch protocols.',
    };
  }

  // 11. Executive meeting summary
  // Default or executive summary query
  return {
    answer: `Executive Programme Health Summary: Across ${filters.selectedState !== 'All' ? filters.selectedState : 'all 4 participating states'} (${filters.dateRange.toUpperCase()} period), ${aggregates.womenRegistered.toLocaleString()} pregnant women have been registered, achieving ${aggregates.facilityDeliveryRate}% formal facility delivery and ${aggregates.avgAncCompletion}% ANC completion against key programme targets.`,
    observations: [
      `Care Navigation: High-risk pregnancy follow-up is at ${aggregates.highRiskFollowUpRate}% (Target: ≥ 90%), with ${aggregates.totalHighRisk.toLocaleString()} high-risk mothers identified by validated ARS screening.`,
      `Outcome Safety: Recorded maternal mortality incidence is ${aggregates.recordedMortalityIncidence} per 100,000 deliveries (${aggregates.totalMaternalDeaths} cases), well below the programme threshold of 120/100k.`,
      `Facility Reporting: ${aggregates.latestMonthOnTimeCount} of ${aggregates.latestMonthTotal} facilities reported on time in the latest cycle (${aggregates.latestMonthOnTimeRate}% compliance).`,
      `Retention Funnel: Highest attrition occurs between ${aggregates.biggestDrop.from} and ${aggregates.biggestDrop.to} (${Math.round(aggregates.biggestDrop.pct)}% drop-off).`,
    ],
    benchmarkComparison: {
      metric: 'Formal Facility Delivery',
      currentValue: `${aggregates.facilityDeliveryRate}%`,
      target: '≥ 80%',
      variance: `${aggregates.facilityDeliveryRate - 80} pts vs target`,
      status: aggregates.facilityDeliveryRate >= 80 ? 'success' : 'warning',
    },
    trendAssessment: {
      direction: aggregates.avgAncCompletionDelta >= 0 ? 'Improving' : 'Declining',
      detail: `ANC completion has shifted by ${aggregates.avgAncCompletionDelta >= 0 ? '+' : ''}${aggregates.avgAncCompletionDelta} pts vs the prior comparative window.`,
    },
    suggestedFollowUp:
      'Focus executive resource allocation on establishing hub-and-spoke blood delivery corridors and subsidizing transport between Visit 2 and Visit 3.',
  };
}
